### ISSUE TITLE
Installation errors if wp8 platform exists

### ISSUE THREAD

**Issue by JohnMcLear** [whiteoctober/cordova-plugin-app-version#5]
If wp8 platform is supported install errors.  Plugin works fine in Android tho

```
jose@mint ~/NFC_Ring_Control $ cordova plugin add https://github.com/whiteoctober/cordova-plugin-app-version.git
Fetching plugin from "https://github.com/whiteoctober/cordova-plugin-app-version.git"...
Starting installation of "uk.co.whiteoctober.cordova.AppVersion" for android
Preparing android project
uk.co.whiteoctober.cordova.AppVersion installed on android.
Starting installation of "uk.co.whiteoctober.cordova.AppVersion" for wp8

/usr/local/lib/node_modules/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Cannot read property 'currentVersion' of null
    at checkEngines (/usr/local/lib/node_modules/cordova/node_modules/plugman/src/install.js:68:35)
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:760:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:526:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
jose@mint ~/NFC_Ring_Control $ 
```

**Comment by am** [comment]
If wp8 is not suppported this issue could be closed.
