### ISSUE TITLE
When I tried to install the plugin, I got error message:  Object #<Object> has no method 'parse'

### ISSUE THREAD

**Issue by emmychen** [whiteoctober/cordova-plugin-app-version#75]
$ cordova plugin add cordova-plugin-app-version

Fetching plugin "cordova-plugin-app-version" via npm
Installing "cordova-plugin-app-version" for ios
Failed to install 'cordova-plugin-app-version':TypeError: Uh oh!
Object #<Object> has no method 'parse'
    at handlers.js-module.install (/Users/emmychen/cordova/ionic/mathwp/platforms/ios/cordova/lib/plugman/pluginHandlers.js:156:66)
    at Object.ActionStack.process (/Users/emmychen/cordova/ionic/mathwp/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Plugman.addPlugin (/Users/emmychen/cordova/ionic/mathwp/platforms/ios/cordova/lib/plugman/Plugman.js:82:20)
    at Api.addPlugin (/Users/emmychen/cordova/ionic/mathwp/platforms/ios/cordova/Api.js:187:53)
    at handleInstall (/opt/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:601:6)
    at /opt/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:385:28
    at _fulfilled (/opt/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/opt/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/opt/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /opt/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
Error: Uh oh!
Object #<Object> has no method 'parse'

**Comment by jeroendeswaef** [comment]
The `parse` method is only available from a more recent node.js version
[See here how to upgrade node.js](https://davidwalsh.name/upgrade-nodejs)

**Comment by lorensr** [comment]
@jeroendeswaef I'm unable to upgrade my node version. Do you know what I'd need to change in a fork of this package to prevent plugman from using `parse`?

**Comment by robations** [comment]
What version of node is required? I'm trying to stick with 4.x as long as possible to avoid churn. Every single time I dip into a cordova project a whole !@£$%ton of stuff updates and breaks... :( :) Hard to blame anyone for this when everyone's trying to push forward and improve software but it's very frustrating. Also, I believe it's possible to constrain the version of node using the `engines` property in package.json, maybe that would be useful here.

**Comment by Drarok** [comment]
As this appears to be `plugman` or Node-related, I'm going to close it.
